"""
Slack Integration Module
Posts formatted analysis results to Slack channels
"""

import os
from typing import Dict
import json

class SlackPoster:
    """Posts analysis results to Slack"""
    
    def __init__(self, webhook_url: str = None):
        """Initialize with Slack webhook URL"""
        self.webhook_url = webhook_url or os.environ.get("SLACK_WEBHOOK_URL")
    
    def post_analysis(self, results: Dict) -> bool:
        """
        Post analysis results to Slack
        Returns True if successful
        """
        message = self._format_message(results)
        
        # In production, this would use requests library to POST to webhook
        # For portfolio demo, we just print the formatted message
        print("\n=== Slack Message (Demo) ===")
        print(json.dumps(message, indent=2))
        
        return True
    
    def _format_message(self, results: Dict) -> Dict:
        """Format analysis results as Slack Block Kit message"""
        
        # Create urgency indicator
        urgency_emoji = "🔴" if results['high_priority_count'] > 5 else "🟡"
        
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "📊 Weekly VoC Analysis"
                }
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Total Feedback:*\n{results['total_analyzed']}"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*High Priority:*\n{urgency_emoji} {results['high_priority_count']}"
                    }
                ]
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Analysis Summary:*\n{results['summary'][:500]}..."
                }
            },
            {
                "type": "divider"
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "Generated by Voice of Customer Synthesizer"
                    }
                ]
            }
        ]
        
        return {"blocks": blocks}

# Example usage
if __name__ == "__main__":
    # Demo results
    demo_results = {
        'total_analyzed': 1000,
        'high_priority_count': 23,
        'summary': 'Key themes: Payment processing issues, mobile loading performance, unclear error messages.'
    }
    
    poster = SlackPoster()
    poster.post_analysis(demo_results)
    